.husky/_/commit-msg
commitlint.config.js
package.json
yarn.lock

commitlint 라이브러리 적용
<br/>
commitlint library 설치 및 config 파일(기본 설정) 적용
git commit 시 합의된 컨벤션
feat, fix, refact 등을 언급하지 않을 경우 error 후 commit 취소됩니다.
또 다른 적용할 내용이 있을지
적용시키고 싶은 규칙이 있다면 요청바람

Feat: commitlint 라이브러리 적용

---

README.md
package.json
yarn.lock

develop -> Main 병합 conflict 문제
develop 브랜치에서 main 브랜치로 병합 시 발생한 충돌(conflict) 해결
충돌 파일 확인 및 수동 병합 진행
1. main 브랜치에서 git pull 후 병합 결과 확인
2. 로컬 서버 실행 → 주요 화면 UI/동작 확인
3. 충돌 처리된 파일 중심으로 변경 사항 검토

Main 병합 conflict 문제

---

package.json
src/layout/Layout.tsx
src/layout/index.ts
src/layout/nav/Nav.tsx
src/layout/nav/index.ts
src/main.tsx
src/pages/Booth.tsx
src/pages/Login.tsx
src/pages/Main.tsx
src/pages/Map.tsx
src/pages/Performance.tsx
src/pages/index.ts
yarn.lock

react-router 를 통한 페이지 라우팅 처리
react-router 설치
routes를 통해 페이지 리스트
layout 기본 구조 및 outlet 반영
네비게이션 클릭을 통해 페이지 전환 확인
추가 라우팅 사항
잘못된 설정이나 추가 설정 필요 시 연락바람

configuaret routing

---

src/styles/global.ts

vh 설정 시 화면 넘침 해결
vh 설정 시 화면 넘침 해결

edit content overflow

---

src/layout/Layout.styles.ts
src/layout/Layout.tsx
src/styles/global.ts

상단 스와이프 새로고침 방지 및 좌우 스와이프 이동 방지
css 속성을 통해 상단 스와이프 방지
좌우 eventPrevenDefault를 통해 스와이프 방지
좌우 스와이프 및 상단 스와이프

reload prevent

---

src/layout/Layout.tsx
src/layout/nav/Nav.styles.ts

history stack 초기화, nav fixed -> absolute 변경
nav 포지션
absolute로 변경
history.pushState 항상 초기화

feat: history stack 초기화, nav fixed -> absolute 변경

---

package.json
src/layout/Layout.tsx
src/layout/nav/Nav.tsx
src/utils/history.ts
src/utils/index.ts
tsconfig.app.json
vite.config.ts
yarn.lock

뒤로가기, 앞으로 가기 제거
history 사용 뒤로가기 버튼 전용 뒤로가기 취소
Nav, layout 스와이프 막기

뒤로가기, 앞으로 가기 제거

---

src/layout/Layout.tsx
src/layout/nav/Nav.tsx

feat: swipe 기준 10 -> 20으로 변경
feat: swipe 기준 10 -> 20으로 변경
스와이프
10 - 20 - 30 비교 예정

feat: swipe 기준 10 -> 20으로 변경

---

src/styles/global.ts

feat: overscroll-behavior-x none 추가
overscroll-behavior-x none 추가

feat: overscroll-behavior-x none 추가

---

src/layout/main/Main.styles.ts
src/layout/main/Main.tsx
src/layout/nav/Nav.tsx
src/layout/nav/nav-item.tsx
src/stores/useLayoutStore.ts

page slide animation 제거
page slide animation 관련 스토어, handler 제거
- 렌더링이 비효율적이라 제거

page slide animation 제거

---

index.html
vite.config.ts

아이폰 상단 바 검은색 이슈 해결
html meta 태그 수정 theme-color 추가
vite.config 파일 display-override 속성 추가

fix: ios header status bar black color issue

---

src/components/image-text-icon-frame/ImageTextIconFrame.styles.ts

style: 폰트 theme.ts 적용
theme.ts에 있는 font로 style 적용

Fix -> style: 폰트 theme.ts 적용

---

src/components/tabs/Tabs.styles.ts

fix: transparent 오타 수정
Tabs styles.ts transparent 오타 수정
-> active 상태일 때 글자가 작아지는 애니메이션 디자이너님한테 여쭤보니 어색하다고 합니다! 
차라리 Tab Nav에 넣는 게 어떠냐고 하시는데 나중에 회의 떄 얘기 나눠보면 좋을 것 같습니다.

fix: transparent 오타 수정

---

src/layout/nav/Nav.styles.ts
src/layout/nav/Nav.tsx
src/styles/global.ts
src/styles/theme.ts

반응형 설계(브라우저 사이즈 처리, root 포지션 변경), 단위 변경(px -> rem)
반응형 설계
- 브라우저일 경우, 1024px 화면 이상 시 가운데 정렬 및 좌우 여백으로 변경
- root 포지션 fixed 설정으로 340px 이하로 내려갈 경우 축소 처리
단위 변경
- theme fonts px -> rem
- nav fontsize, width, height 등 px > rem 변경
화면 리사이징 테스팅

반응형 설계(브라우저 사이즈 처리, root 포지션 변경), 단위 변경(px -> rem)

---

vite.config.ts

SVGR rem 크기 미반영 문제
SVGR rem 크기 미반영 문제
- vite svgr 사용시 viewBox가 자동으로 제거됨
- 제거되지 않도록 옵션 수정

[긴급] SVGR rem 크기 미반영 문제

---

src/types/styled-components.d.ts

Theme 자동 완성 미반영 문제
index.ts 파일 삭제 미반영

Theme 자동 완성 미반영 문제

---

src/components/nav-bar/NavBar.tsx
src/components/nav-bar/NavBar.types.ts

fix: SearchNavBar 수정

---

.gitignore
src/types/kakao-maps.d.ts

.env 깃무시 및 지도 관련 선언파일 추가
1. 지도 초기 작업을 위한 선언파일을 추가합니다.
2. 환경변수 보안을 위한 .gitignore 에 항목을 추가합니다.

.env 깃무시 및 지도 관련 선언파일 추가

---

src/pages/performance/PerformanceDetail.styles.ts
src/pages/performance/PerformanceDetail.tsx

상세정보 페이지 key값 입력 &  $ 접두사 붙이기
- map 배열 상위 태그에 key값 입력
- $ 접두사 붙이기

상세정보 페이지 key값 입력 &  $ 접두사 붙이기

---

src/pages/performance/TimeTable.styles.ts
src/pages/performance/TimeTable.tsx

transition $ 접두사 추가 
- transition $ 접두사 추가

transition $ 접두사 추가

---

src/components/notification/Notification.tsx

fix: notification 컴포넌트 아이콘 import 형식으로 변경

fix: notification 컴포넌트 아이콘 import 형식으로 변경

---

src/pages/performance/TimeTable.styles.ts
src/pages/performance/TimeTable.tsx

타임테이블 여백 제거 및 언마운트 시 내브바 다시 생성
- 타임테이블 여백 제거 
- 언마운트 시 내브바 다시 생성
https://github.com/user-attachments/assets/f27b9379-05d3-4ae0-986d-1d5c47420026
- 공연 페이지에서 타임테이블 들어갈 시 가로 슬라이드 안 생기면 OK
- 다시 공연페이지로 돌아갈 때 내브바 생기면 OK

타임테이블 여백 제거 및 언마운트 시 내브바 다시 생성

---

src/components/image-text-frame/ImageTextFrame.styles.ts
src/components/image-text-frame/ImageTextFrame.types.ts
src/components/image-text-frame/ImageTextFrameWithOrganization.tsx
src/components/image-text-frame/ImageTextFrameWithTime.tsx

Image Text Frame 활성화 스타일 여부 속성 추가
```javascript
<ImageTextFrameWithOrganization
width="100%"
image={''}
title={'PubName'}
organization={'organization Name'}
canPickup={true}
activeStyle={false}
/>
```

[공통 컴포넌트]Image Text Frame 활성화 스타일 여부 속성 추가

---

src/components/tabs/Tabs.tsx
src/components/tabs/Tabs.types.ts
src/components/tabs/index.ts
src/pages/Main.tsx

multitabs 추가
- Multitabs 추가
```
import { useState } from 'react';
import { MultiTabs } from '@/components/tabs/Tabs';
const DAY_OPTIONS = ['1일차', '2일차', '3일차'] as const;
export default function Main() {
const [selectedDays, setSelectedDays] = useState<string[]>([]);
return (
<div style={{ padding: '2rem' }}>
<h2>공연 일자 선택</h2>
<MultiTabs
tabs={[...DAY_OPTIONS]}
activeTab={selectedDays}
onTabClick={(updated) => setSelectedDays(updated)}
toggle
/>
<div style={{ marginTop: '1rem' }}>
<strong>선택된 일자:</strong> {selectedDays.length > 0 ? selectedDays.join(', ') : '없음'}
</div>
</div>
);
}
```

multitabs 추가

---

src/components/notification/Notification.tsx
src/components/notification/Notification.types.ts

Notification - onClose 콜백 함수 추가 및 타입 정의 수정
큰 문제 없다면 빠른 approve 부탁드립니당

[공통 컴포넌트] Notification - onClose 콜백 함수 추가 및 타입 정의 수정

---

src/components/bluebuttons/BlueButton.style.ts
src/components/bluebuttons/BlueButton.types.ts

feat: bluebutton 사이즈 추가
feat: bluebutton 가장 큰 사이즈 추가
<BlueButton label="등록하기" size="larger" onClick={handleClick} />

feat: bluebutton 사이즈 추가

---

src/components/bluebuttons/BlueButton.style.ts

BlueButton: 패딩 스타일 수정
padding: ${({ $size }) => {
switch ($size) {
case 'small':
return '0.25rem 1rem';
case 'larger':
return '0.75rem 1.25rem';
default: // large, large-header 공통
return '0.5rem 1.25rem';
}
}};

BlueButton: 패딩 스타일 수정

---

src/components/input-stepper/InputStepper.styles.ts
src/features/booth/components/BoothLocation.styles.ts
src/features/booth/components/BoothLocation.tsx
src/features/waiting/components/WaitingModal.tsx

주점 상세 페이지 미적용 수정
input-stepper input field color white
location component 지도 버튼 아이콘 추가 색상 추가

주점 상세 페이지 미적용 수정

---

src/constants/main/Members.ts
src/features/main/components/madeby/Card.styles.ts
src/features/main/components/madeby/Card.tsx
src/features/main/components/madeby/Card.types.ts
src/features/main/components/madeby/index.ts
src/main.tsx
src/pages/index.ts
src/pages/main/notice/MadeBy.styles.ts
src/pages/main/notice/MadeBy.tsx

[페이지] 만든이들 페이지 구현
https://github.com/user-attachments/assets/00a1b3f1-6102-4b72-8fe7-c00fb54dee3b

[페이지] 만든이들 페이지 구현

---

src/features/waiting/components/TablingCardList.styles.ts
src/features/waiting/components/TablingCardList.tsx
src/pages/user/User.styles.ts
src/pages/user/User.tsx

테이블링 카드 디자인 피드백 반영
카드 확장 축소 애니메이션 시 글자 확장 문제 <- opacity 변경
navigate 추가

테이블링 카드 디자인 피드백 반영

---

index.html
src/main.tsx
vite.config.ts

스플래시 이후 흰화면 로딩 문제
스플래시 이후 리액트 root 렌더링까지 흰화면이 구성되는 문제를 해결하기 위한 몇가지 테스트 PR입니다
- index.html에 직접 style 추가
- 스플래시 div 넣고 로딩시 제거
앱 실행

스플래시 이후 흰화면 로딩 문제

---

src/features/map/header/Header.styles.ts
src/features/map/header/Header.tsx

fix: expanded를 $expanded로 변경

---

src/constants/festival/dates.ts
src/pages/map/MapPage.tsx
src/utils/dateUtils.ts

현재 날짜 기반 자동 일차 적용 #182 
const/festival/dates.ts 에서 날짜값 바꿔가면서 테스트 해보시면 됩니다.
지도페이지 상단에 1일차 2일차 3일차 이 부분 초기값이 자동 적용되면 됩니다.

[지도 페이지] 현재 날짜 기반 자동 일차 적용

---

src/pages/map/MapPage.tsx

fix: 언마운트 시 네비게이션 바 원상복구
https://github.com/user-attachments/assets/bae15f26-0770-49b8-aac0-f4b326770949

fix: 언마운트 시 네비게이션 바 원상복구

---

.env-development
.env-production

env files testing - vercel 에러
env files testing - vercel 에러

env files testing - vercel 에러

---

src/constants/performance/SingerInfo.ts
src/pages/performance/Performance.tsx

fix: 외부링크 및 내부 링크 수정
- 외부링크 및 내부 링크 수정
- 공연 페이지에서 노티나 공지사항 -> 공지사항 페이지 이동
- 10cm, ftisland, idle 곡 정보 수정

fix: 외부링크 및 내부 링크 수정

---

src/features/login/modal/LoginModal.tsx
src/features/lost/components/main/Registration.tsx
src/features/main/components/user/Footer.tsx
src/hooks/useModal.ts
src/layout/nav/Nav.tsx
src/pages/user/User.tsx

비로그인 사용자 차단 기능
useAuthStore isLoggined 상태를 사용해 페이지 접근을 차단합니다
기존 로그인 모달 - 불편해도 이용하기 기능을 추가합니다
- 모달 제거 타임아웃 3초에서 0초로 변경

비로그인 사용자 차단 기능

---

src/features/main/components/user/AppInstallPrompt.tsx

safari standalone 설치 유도 제거
홈화면 추가 후에도 한번은 뜨는 문제를 수정하기 위해 standalone으로 판단 실행

fix: safari standalone 모달 안뜨게 처리

---

src/features/main/components/user/AppInstallPrompt.tsx

standalone 이면 설치 유도 모달 안뜨게 설정
standalone 판별 내용 변경

standalone 이면 설치 유도 모달 안뜨게 설정

---

src/pages/performance/TimeTable.tsx

fix: key props 루트로 이동
- key props 루트로 이동
- 콘솔에 에러나는 거 해결~! 
-

fix: key props 루트로 이동

---

src/features/lost/components/main/NoResultMessage.tsx

fix: noresultmessagetitle 적용
- style 이름을 title이 아닌 Message로 되어있는 오타 발견 및 수정

fix: noresultmessagetitle 적용

---

src/components/modal/Modal.style.ts
src/features/alarm/components/AlarmModal.styles.ts
src/features/alarm/components/AlarmModal.tsx
src/features/main/components/user/AppInstallPrompt.styles.ts
src/layout/Layout.tsx
src/main.tsx
src/pages/login/Login.tsx
src/pages/main/Main.tsx

유저 first land flow 구성
사용자 처음 앱 실행 시
로그인 으로 이동 -> 로그인에서 알람 확인 모달 생성 -> 메인으로 이동 -> 메인에서 앱 설치 유도 모달 출력

유저 first land flow 구성

---

src/features/map/header/Header.styles.ts
src/features/map/header/Header.tsx
src/features/map/header/Header.types.ts
src/pages/map/MapPage.tsx

[지도] 뒤로가기(초기화) 버튼 추가 및 관련 핸들러 구현
카테고리와 마커를 모두 없앨 목적의 뒤로가기 버튼을 만들었습니다. (기획자 의도 맞음)
https://github.com/user-attachments/assets/ee240b67-dde0-4e27-ac4f-5e5d542328c9

[지도] 뒤로가기(초기화) 버튼 추가 및 관련 핸들러 구현

---

src/hooks/useDebounce.ts
src/main.tsx
src/pages/map/MapPage.tsx
src/pages/map/SearchPage.styles.ts
src/pages/map/SearchPage.tsx

[지도] 검색기능 구현
제목과 카테고리로 검색이 가능합니다
누르면 지도로 이동합니다
이제 /map/{id}로 아이디를 통한 지도이동이 가능합니다
https://github.com/user-attachments/assets/136f5b17-bc59-4205-a102-a4c98236ffda

[지도] 검색기능 구현

---

src/features/booth/components/BoothList.tsx

주점 오픈 알림 alert 버튼 제거
제목과 내용이 같습니다
주점 - 주점 리스트 페이지 확인

주점 오픈 알림 alert 버튼 제거

---

src/hooks/useKakaoMap.ts
src/types/kakao-maps.d.ts

[지도] 푸드트럭 및 플리마켓 구역 표시
타입 선언
영역 표시
제거 로직
https://github.com/user-attachments/assets/2b2a4bb2-dfc1-4a8d-9d69-11a0a238dba2

[지도] 푸드트럭 및 플리마켓 구역 표시

---

src/pages/main/made/MadeBy.styles.ts

fix: padding bottom 100px로 변경
fix: padding bottom 100px로 변경

fix: padding bottom 100px로 변경

---

src/features/waiting/components/TablingCardList.tsx

fix: 고유 id key 변경

---

src/features/alarm/components/AlarmModal.tsx
src/services/fcm/notificationPermission.ts
src/services/login.ts

fix: token 미반영 문제 수정

---

src/services/fcm/notificationPermission.ts

fix: token

---

src/main.tsx

feat: 타임테이블 접근 제한

---

src/pages/booth/Booth.tsx
src/pages/booth/BoothDetail.tsx

QA반영(탭, 주점 디테일)
탭  순서 변경(좋아요, 주점 리스트 순으로)
주점 디테일 스크롤 맨 위로
디테일 페이지 접속,
주점 탭

QA반영(탭, 주점 디테일)

---

src/pages/booth/BoothDetail.styles.ts
src/pages/booth/BoothDetail.tsx

하단 보더 제거 QA
section에 해당하는 bottom border 제거
주점 상세 페이지 접속

하단 보더 제거 QA

---

src/components/nav-bar/NavBar.styles.ts
src/layout/Layout.styles.ts
src/layout/Layout.tsx
src/pages/main/Main.styles.ts
src/pages/main/made/MadeBy.styles.ts

NavBar fixed처리

---

src/components/nav-bar/NavBar.types.ts
src/constants/search/SEARCH_CONSTANTS.ts
src/pages/map/SearchPage.styles.ts
src/pages/map/SearchPage.tsx

[지도/검색] 최근검색기능 제거 및 추천검색어 변경

---

src/constants/map/CategoryNotifications.ts

fix: 공지사항 제목 및 경로 수정

---

src/constants/map/MapData.ts

fix: 주점(술체역학) 위치 좌표 수정

---

src/components/nav-bar/NavBar.styles.ts
src/components/nav-bar/NavBar.tsx

searchnav width 조정

---

src/constants/main/Members.ts
src/pages/main/made/MadeBy.tsx

fix: 프로트 -> 프론트엔드로 변경  
- fix: 프로트 -> 프론트엔드로 변경

fix: 프론트 -> 프론트엔드로 변경

---

index.html
src/features/like/components/LikeButton.tsx
src/main.tsx
src/utils/inAppValid.ts

인앱 접속 시 사파리로 강제 이동
이탈율을 낮추기 위해 카카오톡, 라인으로 접속하는 경우 외부 브라우저를 통해 접속할 수 있도록 강제로 이동

인앱 접속 시 사파리로 강제 이동

---

src/constants/booth/booth.ts

- fix: 융합시스템 오탈자 수정
- 융합시스템 오탈자 발견 -> 가격 수정

fix: 융합시스템 오탈자 수정

---

src/features/like/components/LikeButton.styles.ts
src/features/like/components/LikeButton.tsx

좋아요 버튼 z인덱스 추가
likeButton zIndex: 80

좋아요 버튼 z인덱스 추가

---

index.html

index.html script 함수 제거
index.html script에서 splash_screen을 display:none을 반복출력 문제 수정

index.html script 함수 제거

---

src/components/tab-nav/TabNav.styles.ts
src/features/rank/components/PubRank.styles.ts

tab container 배경색 추가, relative 포지션
tab Nav container에 배경색 black 추가
funnel relative position 적용

tab container 배경색 추가, relative 포지션

---

src/components/tab-nav/TabNav.styles.ts
src/features/booth/components/BoothList.styles.ts
src/features/rank/components/PubRank.styles.ts
src/pages/booth/Booth.styles.ts

Funnel Main margin top 제거
Funnel Main margin top 제거

Funnel Main margin top 제거

---

src/components/tab-nav/TabNav.styles.ts

tab nav bottom underline bottom -1px로 변경
tab nav bottom underline bottom -1px로 변경

tab nav bottom underline bottom -1px로 변경
